from otree.api import (
    models, widgets, BaseConstants, BaseSubsession, BaseGroup, BasePlayer,
    Currency as c, currency_range
)

import random

doc = """
Captcha quiz, release 1.0.2, Made by JJ(jaejun.lees@gmail.com)
"""


def cmp(a, b):
    n, m = len(a), len(b)
    if n > m:
        # Make sure n <= m, to use O(min(n,m)) space
        a, b = b, a
        n, m = m, n

    current = range(n + 1)
    for i in range(1, m + 1):
        previous, current = current, [i] + [0] * n
        for j in range(1, n + 1):
            add, delete = previous[j] + 1, current[j - 1] + 1
            change = previous[j - 1]
            if a[j - 1] != b[i - 1]:
                change = change + 1
            current[j] = min(add, delete, change)

    return current[n]


def distance_and_ok(input_text, reference_text, max_error_rate):
    error_threshold = len(reference_text) * max_error_rate
    distance = cmp(input_text, reference_text)
    ok = distance <= error_threshold
    return distance, ok


class Player(BasePlayer):
    total_round_num = models.IntegerField()
    transcribed_text = models.StringField()
    cmp_dst = models.IntegerField()




class Constants(BaseConstants):
    name_in_url = 'captcha_quiz'
    players_per_group = None
    progress_bar = True
    reference_texts = [
        "W93BX",
        "JA3V8",
        "RBSKW",
        "HJ9PV",
        "TSMS9",
        "459CT",
        "R84CH",
        "D4TSH",
        "3M56R",
        "HAPK3", #10
        "VSJS",
        "CJR69H",
        "YBJWY",
        "BD8W",
        "ARKUH",
        "PRRCBU",
        "WPVA",
        "VEHKX",
        "5UDWEJ",
        "5RRT9R", #20
        "8NWTTS",
        "CSBHT",
        "U5BS89",
        "KR9RY",
        "WNW6",
        "TYXXWS",
        "SRXK",
        "36HX",
        "KVW34",
        "SE9K", #30
        "N3SAPS",
        "9HPBT",
        "SCTX5S",
        "DMJCW",
        "MUAR6",
        "KNKK",
        "CKSP",
        "BNR6",
        "PWXM",
        "4VJWSR", #40
        "5X8PTP",
        "JNCSD",
        "WVVYUM",
        "DT99Y",
        "DX4BYP",
        "UUSES4",
        "HDDC",
        "H9U5NP",
        "JNHU",
        "5AUCM5", #50
        "VW8UA",
        "WSUR",
        "46SUNS",
        "RVE8",
        "BC33N",
        "MSH3JM",
        "HJMKP",
        "W64S",
        "834JUB",
        "NUB6V", #60
        "MCVCMR",
        "BAT5",
        "XEJM54",
        "5CCUN",
        "WXWD",
        "9WMYW4",
        "R83PSM",
        "9YNNC",
        "89W8HP",
        "54WTV", #70
        "YNAVCA",
        "4XCCA",
        "DDBW5",
        "W89CYX",
        "X5WSD",
        "EN6BBA",
        "MTA6",
        "HRB4N",
        "9XAPK",
        "DWBHMC", #80
        "5VN3",
        "R45W",
        "KNMPC",
        "U9PN9",
        "59UX",
        "RB3C",
        "P5E4",
        "P94JJ",
        "CNSY",
        "9TSMN3", #90
        "JVRM",
        "MNV6V",
        "UPW5DJ",
        "P3D9",
        "BCXD",
        "KJWM6J",
        "DE696P",
        "JTDE",
        "9STR",
        "JRM5", #100
        "V9PB6",
        "NDRA",
        "KA8D4P",
        "H54VDC",
        "A93N6",
        "WCKCT8",
        "EWNJ",
        "M3N3US",
        "93N5",
        "STRP9T", #110
        "W3U3",
        "X5DAHB",
        "SCTJA4",
        "W9WRSE",
        "6ETE34",
        "DWMTSC",
        "RMR9",
        "HDPA",
        "4Y5XD",
        "NXD6", #120
        "893BN", 
        "3YSY",
        "YKNC",
        "V39MT",
        "J5VBX",
        "CMD6",
        "NTAW",
        "AEXAJ",
        "ACPSKW",
        "BJJ9", #130
        "9XWTCR",
        "S4UAS4",
        "4634PW",
        "UMKT6R",
        "VMJT5A",
        "B3TC49",
        "XYDMP8",
        "CYA9N",
        "UB8YY",
        "H6SEX", #140
        "XDTS",
        "PMYWU",
        "NCVJB",
        "WM63U",
        "UJVP6C",
        "YKCAC6",
        "DE3E3",
        "9N54RJ",
        "PXUA",
        "TVU4UT", #150
        "KEK8",
        "SNDMDW",
        "KKJW",
        "3N4RA",
        "BTP6T9",
        "8BU959",
        "SCYKP",
        "4P6VY",
        "RW4RT",
        "YP83R5", #160
        "8C4J89",
        "3MN5VK",
        "3T536K",
        "E3AUK",
        "CUHUKY",
        "B4WS8",
        "TPWPJ3",
        "8EV5",
        "JR4B8V",
        "DW89", #170
        "V9N43",
        "KTB8",
        "WEMWN",
        "VX86",
        "PNAT",
        "WEMCH",
        "SD4384",
        "TWBD53",
        "DMY4A",
        "8C44W4", #180
        "MBAR",
        "6RYN",
        "H54PS9",
        "43MVC",
        "RUC8EN",
        "A56PE9",
        "RTK85",
        "X6XWUY",
        "UYA6Y",
        "J43BYY", #190
        "939R",
        "9X6S",
        "55C54",
        "H4MR",
        "RD9R",
        "X88ESN",
        "ETYK",
        "EKPJ",
        "AS6C",
        "4PDKJP", #200
        "S6EM",
        "CCAYC",
        "EYK99J",
        "3PMK",
        "RST3YC",
        "BS5DMR",
        "DA3M",
        "6NBYV",
        "8UJT4H",
        "YMKSV", #210
        "UBAB3",
        "TAERS",
        "BXEAH",
        "KWAKJ",
        "6BMP",
        "UHWX49",
        "CN43W9",
        "BKV9",
        "B6VMS",
        "DRYN8T", #220
        "863P",
        "XD9E",
        "TP9N64",
        "B6CVDH",
        "9WRN",
        "MDB5M",
        "E9AE",
        "CD6EA",
        "D98HM9",
        "5SRU", #230
        "C6XXR",
        "6VEB",
        "3HR5",
        "CEHC", 
        "NUUA",
        "SBCRY",
        "JYSEAT",
        "Y5WT",
        "9KWW",
        "TREC3X", #240
        "MHK8N",
        "RADHA",
        "MX5BX9",
        "UM8J9E",
        "9P5R",
        "XPVN",
        "4SN6",
        "EWCM5T",
        "STUU",
        "JXV43", #250
        "YE6K3",
        "3YYET6",
        "4JTD",
        "YDWEE",
        "U8CH6",
        "VP6BB",
        "EMRNE",
        "8RB89R",
        "ECA5M",
        "UCPX", #260
        "D5W6A",
        "A58XR",
        "USKUPD",
        "DBHPD",
        "83CP3",
        "CHCX",
        "DWPNEY",
        "94UDA",
        "K8HT",
        "KTSX9D", #270
        "9CRSKB",
        "D4BS",
        "4HR6",
        "YASSW",
        "NPSRKR",
        "RPRH",
        "H4NY",
        "UBVC99",
        "Y6T8R",
        "A8M8R",  #280
        "4NXP",
        "APX3MU",
        "JDH4U",
        "6VJA",
        "KWYT",
        "JA3CB",
        "VRY8",
        "CHAW",
        "W8NT8R",
        "8NPU", #290
        "X46P",
        "NCXR",
        "WTPHTA",
        "ECNPX",
        "5KHX4H",
        "CPUK",
        "3CY9",
        "TRPSD",
        "KYKSXE",
        "5S49T", #300
        "NVKVP6",
        "3VSV",
        "K45K",
        "M35JES",
        "CEJJ",
        "WVH6",
        "J94DN",
        "WKSAM6",
        "8BEM",
        "UT86MW", #310
        "XYWY",
        "3A4V4",
        "S8UPJC",
        "BW4SST",
        "ANPU44",
        "TSVTH",
        "MET83C",
        "DA3DE",
        "VV3Y",
        "NK99X", #320
        "WXBX",
        "KBCAA4",
        "AKMXE",
        "UWK6A9",
        "BSWR8",
        "KUXK",
        "U48YR",
        "HYPR4",
        "CDTVR",
        "MD56S", #330
        "BXMW69",
        "SD4S",
        "EKHA4",
        "5DBX",
        "HRJPC",
        "KP8SJ",
        "ECVR8",
        "DTTDT",
        "KMC3UA",
        "W65ENC", #340
        "E66EJ9",
        "35UA5",
        "BRNVX4",
        "8C65",
        "3YPB",
        "55BKR",
        "NRVT9V",
        "PEW346",
        "U3RWV",
        "44X6NW", #350
        "XTMK",
        "8SXSR",
        "WD649",
        "959N5",
        "SKNUY",
        "4T9UCX",
        "R9TD",
        "CSHD",
        "B9B86",
        "MNHN45", #360
        "HYPP3V",
        "5CSYT",
        "JM5E",
        "W93NV",
        "68WH",
        "CTR5",
        "6TT3B",
        "B598",
        "U9ACW",
        "TPPVU", #370
        "VJK9KM",
        "PBU5",
        "BKS34",
        "S66K4",
        "TV9KJ",
        "99TES",
        "ESTU",
        "9PU6C",
        "W6ERRM",
        "W6DK", #380
        "DH54V",
        "3MP6V",
        "DVE5",
        "6YEBH",
        "UXD5",
        "WXDD",
        "DR9KR3",
        "EU3XXW",
        "EW8XU",
        "8TVB4C", #390
        "RNUS",
        "PX6C",
        "WMD5",
        "Y8JV",
        "HX34J",
        "A88KJ",
        "BAP3",
        "U5K3",
        "M6RVM",
        "KET6", #400
        "BTXA",
        "XBPR",
        "J9DK8",
        "6HUY",
        "H6D3",
        "49BSSS",
        "NY9EB",
        "A6EWPP",
        "38H4",
        "8TED", #410
        "RBVJ6",
        "AM9V",
        "3K3P",
        "VVJHS",
        "8NXV5",
        "B9UHA",
        "CHD8",
        "S9PBR",
        "S86DY6",
        "R5N8M", #420
        "AHD5",
        "YUEAP",
        "YHU3VH",
        "3KDV9B",
        "NJ6RR",
        "H3AN",
        "RYT4",
        "DYNT55",
        "VPA84T",
        "XC9Y", #430
        "6YJB4",
        "EDHKV3",
        "H4W6KD",
        "C9ET",
        "5XPK",
        "JNKS",
        "HSNAS",
        "PPPJ8",
        "CPWHBM",
        "KTYPA", #440
        "EV5XKR",
        "VEN9UA",
        "438XM6",
        "W4N4M",
        "88AB5T",
        "8D8NA6",
        "YPECPV",
        "WCERWB",
        "Y9KKC",
        "XUBVR", #450
        "YYP3",
        "BX9CE",
        "CCN8BB",
        "Y5NEB",
        "66DY9",
        "PC6E",
        "DBAKRT",
        "YPNW4",
        "KMJJEP",
        "4TU3N", #460
        "XRHN",
        "B64Y",
        "53386Y",
        "RSY4H9",
        "JXWKS",
        "XWNUE4",
        "V6MK4",
        "TPY3",
        "SCA5N",
        "RWNYYK", #470
        "DXBJ3V",
        "6W8N4K",
        "DXMW34",
        "DVJ9",
        "RR8A5",
        "M5UUTM",
        "W3JNK",
        "BEDR",
        "YCU5BY",
        "U3YATS", #480
        "KN8R5P",
        "BKJKEH",
        "WSAW",
        "8EX6",
        "J6XXUN",
        "DDPT4",
        "M8YH",
        "9MS9",
        "BDYWNH",
        "D8KBN", #490
        "8J46PX",
        "P4SK",
        "3BSR8B",
        "XDPCE",
        "YURE9",
        "YKA59X",
        "YSTKCC",
        "4C8KK",
        "R4U4VS",
        "9CTVY5", #500
        "8M33JB",
        "R8W5KD",
        "JTYK5C",
        "843E",
        "E9SCYU",
        "CKPUM6",
        "RXW8N",
        "JM99",
        "H4D6NC",
        "MVHBD", #510
        "5RRT9R", #20
        "8NWTTS",
        "CSBHT",
        "U5BS89",
        "KR9RY",
        "WNW6",
        "TYXXWS",
        "SRXK",
        "36HX",
        "KVW34",
        "SE9K", #30
        "N3SAPS",
        "9HPBT",
        "SCTX5S",
        "DMJCW",
        "MUAR6",
        "KNKK",
        "CKSP",
        "BNR6",
        "PWXM",
        "4VJWSR", #40
        "5X8PTP",
        "JNCSD",
        "WVVYUM",
        "DT99Y",
        "DX4BYP",
        "UUSES4",
        "HDDC",
        "H9U5NP",
        "JNHU",
        "5AUCM5", #50
        "VW8UA",
        "WSUR",
        "46SUNS",
        "RVE8",
        "BC33N",
        "MSH3JM",
        "HJMKP",
        "W64S",
        "834JUB",
        "NUB6V", #60
        "MCVCMR",
        "BAT5",
        "XEJM54",
        "5CCUN",
        "WXWD",
        "9WMYW4",
        "R83PSM",
        "9YNNC",
        "89W8HP",
        "54WTV", #70
        "YNAVCA",
        "4XCCA",
        "DDBW5",
        "W89CYX",
        "X5WSD",
        "EN6BBA",
        "MTA6",
        "HRB4N",
        "9XAPK",
        "DWBHMC", #80
        "5VN3",
        "R45W",
        "KNMPC",
        "U9PN9",
        "59UX",
        "RB3C",
        "P5E4",
        "P94JJ",
        "CNSY",
        "9TSMN3", #90
        "JVRM",
        "MNV6V",
        "UPW5DJ",
        "P3D9",
        "BCXD",
        "KJWM6J",
        "DE696P",
        "JTDE",
        "9STR",
        "JRM5", #100
        "V9PB6",
        "NDRA",
        "KA8D4P",
        "H54VDC",
        "A93N6",
        "WCKCT8",
        "EWNJ",
        "M3N3US",
        "93N5",
        "STRP9T", #110
        "W3U3",
        "X5DAHB",
        "SCTJA4",
        "W9WRSE",
        "6ETE34",
        "DWMTSC",
        "RMR9",
        "HDPA",
        "4Y5XD",
        "NXD6", #120
        "893BN", 
        "3YSY",
        "YKNC",
        "V39MT",
        "J5VBX",
        "CMD6",
        "NTAW",
        "AEXAJ",
        "ACPSKW",
        "BJJ9", #130
        "9XWTCR",
        "S4UAS4",
        "4634PW",
        "UMKT6R",
        "VMJT5A",
        "B3TC49",
        "XYDMP8",
        "CYA9N",
        "UB8YY",
        "H6SEX", #140
        "XDTS",
        "PMYWU",
        "NCVJB",
        "WM63U",
        "UJVP6C",
        "YKCAC6",
        "DE3E3",
        "9N54RJ",
        "PXUA",
        "TVU4UT", #150
        "KEK8",
        "SNDMDW",
        "KKJW",
        "3N4RA",
        "BTP6T9",
        "8BU959",
        "SCYKP",
        "4P6VY",
        "RW4RT",
        "YP83R5", #160
        "8C4J89",
        "3MN5VK",
        "3T536K",
        "E3AUK",
        "CUHUKY",
        "B4WS8",
        "TPWPJ3",
        "8EV5",
        "JR4B8V",
        "DW89", #170
        "V9N43",
        "KTB8",
        "WEMWN",
        "VX86",
        "PNAT",
        "WEMCH",
        "SD4384",
        "TWBD53",
        "DMY4A",
        "8C44W4", #180
        "MBAR",
        "6RYN",
        "H54PS9",
        "43MVC",
        "RUC8EN",
        "A56PE9",
        "RTK85",
        "X6XWUY",
        "UYA6Y",
        "J43BYY", #190
        "939R",
        "9X6S",
        "55C54",
        "H4MR",
        "RD9R",
        "X88ESN",
        "ETYK",
        "EKPJ",
        "AS6C",
        "4PDKJP", #200
        "S6EM",
        "CCAYC",
        "EYK99J",
        "3PMK",
        "RST3YC",
        "BS5DMR",
        "DA3M",
        "6NBYV",
        "8UJT4H",
    ]

    num_rounds = len(reference_texts)
    allowed_error_rates = [0, 0.03]



class Subsession(BaseSubsession):
    total_round_num = models.IntegerField
    def live_bid(self, data, data2):
        total_round_num = data2
    pass


class Group(BaseGroup):
    def live_bid(self, data, data2):
        Subsession.total_round_num = data2
#    pass


